version: "3"
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "ticketflickdb"
      MYSQL_USER: "php_docker"
      MYSQL_PASSWORD: "1234"
    volumes:
      - "./database/ticketflickdb.sql:/docker-entrypoint-initdb.d/ticketflickdb.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
 
